# Revision: 926f7eb525bf, created 2022-06-01 14:36:22.372483

import sqlalchemy as sa

from alembic import op

revision = '926f7eb525bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards', sa.Column('id', sa.Integer(), nullable=False), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'muscles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'workouts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'board_workouts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sort_value', sa.Integer(), nullable=True),
        sa.Column('board_id', sa.Integer(), nullable=True),
        sa.Column('workout_id', sa.Integer(), nullable=True),
        sa.Column('sets_value', sa.Integer(), nullable=True),
        sa.Column('reps_value', sa.Integer(), nullable=True),
        sa.Column('measurement_value', sa.Integer(), nullable=True),
        sa.Column('measurement_unit', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ['board_id'],
            ['boards.id'],
        ),
        sa.ForeignKeyConstraint(
            ['workout_id'],
            ['workouts.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'workout_muscles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('workout_id', sa.Integer(), nullable=True),
        sa.Column('muscle_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['muscle_id'],
            ['muscles.id'],
        ),
        sa.ForeignKeyConstraint(
            ['workout_id'],
            ['workouts.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_muscles')
    op.drop_table('board_workouts')
    op.drop_table('workouts')
    op.drop_table('muscles')
    op.drop_table('boards')
    # ### end Alembic commands ###
