# Revision: dc661bf4ff6e, created 2022-08-17 14:28:16.148326

import sqlalchemy as sa

from alembic import op

revision = 'dc661bf4ff6e'
down_revision = 'a669c4aaeae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_workouts', 'measurement_value', type_=sa.DECIMAL(precision=12, scale=6))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board_workouts', 'measurement_value', type_=sa.Integer())
    # ### end Alembic commands ###
