# Revision: e5ab9f28ac47, created 2022-08-02 19:37:37.306859

from alembic import op
import sqlalchemy as sa


revision = 'e5ab9f28ac47'
down_revision = 'af088451bddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('boards', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'created')
    op.drop_column('boards', 'name')
    # ### end Alembic commands ###
