# Revision: 8ee8c87ea62a, created 2022-08-17 19:39:09.163634

from alembic import op
import sqlalchemy as sa


revision = '8ee8c87ea62a'
down_revision = 'dc661bf4ff6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('board_workouts_board_id_fkey', 'board_workouts', type_='foreignkey')
    op.create_foreign_key(None, 'board_workouts', 'boards', ['board_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'board_workouts', type_='foreignkey')
    op.create_foreign_key('board_workouts_board_id_fkey', 'board_workouts', 'boards', ['board_id'], ['id'])
    # ### end Alembic commands ###
