# Revision: 1f5871599ead, created 2022-08-18 15:06:21.617065

import sqlalchemy as sa

from alembic import op

revision = '1f5871599ead'
down_revision = '8ee8c87ea62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'board_workout_records',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created', sa.DateTime(), nullable=True),
        sa.Column('sets_value', sa.Integer(), nullable=True),
        sa.Column('reps_value', sa.Integer(), nullable=True),
        sa.Column('measurement_value', sa.DECIMAL(precision=12, scale=6), nullable=True),
        sa.Column('measurement_unit', sa.String(), nullable=True),
        sa.Column('board_workout_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['board_workout_id'], ['board_workouts.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_workout_records')
    # ### end Alembic commands ###
